name: CI
on: push
jobs:
  prod-check:
  # Context variables can can be used at any time in the workflow
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    # Default variables can only be used within a runner that is executed (when job is executed)
    # Run is used to run scripts available in the job/runner
      - run: echo "Deploying to production server on branch $GITHUB_REF, custom environment variable is $First_Name"
        env:
          First_Name: Vic
# Example of two jobs that save and downloads artifacts, in this case being a simple text file 
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World" > file.txt
      - uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt
  
  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: file
      - run: cat file.txt
